# Generated by Django 5.2.1 on 2025-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_image', models.ImageField(upload_to='aadhaar/')),
                ('selfie_image', models.ImageField(upload_to='selfie/')),
                ('dob_extracted', models.CharField(blank=True, max_length=20)),
                ('face_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
