services:
  - type: web
    name: aadhar-verification-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn aadhar_face_verification.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: aadhar_face_verification.settings
